server:
  port: 8101

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 182.254.166.73:8001
    gateway:
      routes:
        - id: hello
          uri: http://www.yjf.com:8102/get/getMapping
          predicates:
            - Path=/hello/**
            - Method=GET