server:
  port: 8102

spring:
  cloud:
    sentinel:
      transport:
#        dashboard: 182.254.166.73:8858
        dashboard: localhost:8858
          # 当前应用被sentinel监控的端口
        port: 8102
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"